#!/usr/bin/env bash
set -xeuo pipefail

WEBGYM_SKD_DATASET_DIR=/home/sogang_nlpy/verl/data/webgym_skd
WEBGYM_TOOL_CONFIG_PATH=/home/sogang_nlpy/verl/WebOSWorld/config/tool_config/webgym_rl_tool_config_bundled.yaml
WEBGYM_SYSTEM_PROMPT_PATH="${1:-/home/sogang_nlpy/verl/WebOSWorld/webgym_rl/system_prompt_webgym_rl.txt}"
HF_HUB_ROOT=/home/sogang_nlpy/.cache/huggingface/hub
QWEN35_9B_PATH="${QWEN35_9B_PATH:-${HF_HUB_ROOT}/models--Qwen--Qwen3.5-9B/snapshots/c202236235762e1c871ad0ccb60c8ee5ba337b9a}"
QWEN35_27B_PATH="${QWEN35_27B_PATH:-${HF_HUB_ROOT}/models--Qwen--Qwen3.5-27B/snapshots/fc05daec18b0a78c049392ed2e771dde82bdf654}"
RUN_TS="$(date +%Y%m%d_%H%M%S)"
ASYNC_SKD_EVENT_LOG_PATH="/home/sogang_nlpy/verl/logs/async_skd_events_webgym_${RUN_TS}.jsonl"
ASYNC_SKD_CHUNK_LIVE_LOG_PATH="/home/sogang_nlpy/verl/logs/async_skd_chunk_live_webgym_${RUN_TS}.jsonl"
ASYNC_SKD_TURN_LOG_PATH="/home/sogang_nlpy/verl/logs/async_skd_turns_webgym_${RUN_TS}.jsonl"
if [ "$#" -ge 1 ]; then
    shift
fi

SGLANG_NUMA_BIND_V2=0 \
SGLANG_ENABLE_TORCH_INFERENCE_MODE=1 \
VERL_ASYNC_SKD_SLOW_LOOP_MS=10 \
VERL_SKD_DEBUG=2 \
VERL_ASYNC_SKD_TRACE=2 \
VERL_ASYNC_SKD_CHUNK_TRACE=2 \
VERL_ASYNC_SKD_CHUNK_TRACE_TOPK=5 \
VERL_ASYNC_SKD_CHUNK_TRACE_MAX_TOKENS=64 \
VERL_ASYNC_SKD_EVENT_LOG="${ASYNC_SKD_EVENT_LOG_PATH}" \
VERL_ASYNC_SKD_CHUNK_LIVE_LOG="${ASYNC_SKD_CHUNK_LIVE_LOG_PATH}" \
VERL_ASYNC_SKD_TURN_LOG="${ASYNC_SKD_TURN_LOG_PATH}" \
python3 -m verl.trainer.main_ppo \
    model_engine=veomni \
    "data.train_files=['${WEBGYM_SKD_DATASET_DIR}/train.parquet']" \
    "data.val_files=['${WEBGYM_SKD_DATASET_DIR}/val.parquet']" \
    data.return_raw_chat=True \
    data.train_batch_size=16 \
    data.max_prompt_length=3072 \
    data.max_response_length=24576 \
    data.filter_overlong_prompts=False \
    data.filter_overlong_prompts_workers=64 \
    data.truncation=error \
    data.shuffle=False \
    algorithm.adv_estimator=grpo \
    algorithm.use_kl_in_reward=False \
    actor_rollout_ref.model.path="${QWEN35_9B_PATH}" \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.model.use_fused_kernels=False \
    actor_rollout_ref.actor.use_torch_compile=True \
    reward.custom_reward_function.path=/home/sogang_nlpy/verl/WebOSWorld/webgym_rl/reward_fn_webgym_rl.py \
    reward.custom_reward_function.name=compute_score_webgym_rl \
    distillation.enabled=True \
    distillation.n_gpus_per_node=4 \
    distillation.nnodes=1 \
    distillation.teacher_models.teacher_model.model_path="${QWEN35_27B_PATH}" \
    distillation.teacher_models.teacher_model.num_replicas=4 \
    distillation.teacher_models.teacher_model.inference.name=sglang \
    distillation.teacher_models.teacher_model.inference.tensor_model_parallel_size=1 \
    distillation.teacher_models.teacher_model.inference.gpu_memory_utilization=0.80 \
    distillation.teacher_models.teacher_model.inference.max_model_len=86800 \
    distillation.teacher_models.teacher_model.inference.max_num_batched_tokens=86800 \
    distillation.teacher_models.teacher_model.inference.max_num_seqs=16 \
    +distillation.teacher_models.teacher_model.inference.engine_kwargs.sglang.attention_backend=triton \
    +distillation.teacher_models.teacher_model.inference.engine_kwargs.sglang.mm_attention_backend=fa4 \
    distillation.distillation_loss.loss_mode=forward_kl_topk \
    distillation.distillation_loss.topk=256 \
    +distillation.distillation_loss.forward_kl_topk_impl=logsumexp_gather \
    distillation.distillation_loss.use_task_rewards=False \
    distillation.distillation_loss.use_policy_gradient=False \
    distillation.skd.chunk_size=32 \
    distillation.skd.verify_top_k=1 \
    distillation.skd.max_chunks_per_sample=256 \
    distillation.skd.windowed_training_enabled=False \
    distillation.skd.mask_invalid_action=False \
    actor_rollout_ref.rollout.name=sglang \
    actor_rollout_ref.rollout.mode=async \
    actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.80 \
    actor_rollout_ref.rollout.calculate_log_probs=False \
    actor_rollout_ref.rollout.max_model_len=76800 \
    actor_rollout_ref.rollout.max_num_batched_tokens=76800 \
    actor_rollout_ref.rollout.max_num_seqs=64 \
    actor_rollout_ref.rollout.n=1 \
    actor_rollout_ref.rollout.temperature=0.6 \
    actor_rollout_ref.rollout.top_p=0.95 \
    actor_rollout_ref.rollout.top_k=20 \
    +actor_rollout_ref.rollout.engine_kwargs.sglang.attention_backend=triton \
    +actor_rollout_ref.rollout.engine_kwargs.sglang.mm_attention_backend=fa4 \
    +actor_rollout_ref.rollout.repetition_penalty=1.0 \
    actor_rollout_ref.rollout.agent.num_workers=4 \
    actor_rollout_ref.rollout.agent.default_agent_loop=web_skd_agent \
    +actor_rollout_ref.rollout.agent.agent_loop_manager_class=verl.experimental.async_skd.manager.AsyncSkdAgentLoopManager \
    +actor_rollout_ref.rollout.agent.async_skd_mode=lookahead \
    +actor_rollout_ref.rollout.agent.async_skd_teacher_sticky_carryover=True \
    +actor_rollout_ref.rollout.agent.async_skd_prefetch_limit=16 \
    +actor_rollout_ref.rollout.agent.async_skd_prefetch_worker_target=4 \
    +actor_rollout_ref.rollout.agent.async_skd_max_promoted_per_step=16 \
    +actor_rollout_ref.rollout.custom.enable_qwen3_coder_structured_output=False \
    +actor_rollout_ref.rollout.custom.web_skd_include_a11y=false \
    actor_rollout_ref.rollout.val_kwargs.n=1 \
    actor_rollout_ref.rollout.val_kwargs.do_sample=True \
    actor_rollout_ref.rollout.val_kwargs.temperature=0.6 \
    actor_rollout_ref.rollout.val_kwargs.top_p=0.95 \
    actor_rollout_ref.rollout.val_kwargs.top_k=20 \
    actor_rollout_ref.rollout.multi_turn.enable=True \
    actor_rollout_ref.rollout.multi_turn.max_assistant_turns=10 \
    actor_rollout_ref.rollout.multi_turn.max_user_turns=10 \
    actor_rollout_ref.rollout.multi_turn.max_parallel_calls=5 \
    "actor_rollout_ref.rollout.multi_turn.tool_config_path=${WEBGYM_TOOL_CONFIG_PATH}" \
    "actor_rollout_ref.rollout.multi_turn.system_prompt_path=${WEBGYM_SYSTEM_PROMPT_PATH}" \
    actor_rollout_ref.rollout.multi_turn.format=qwen3_coder \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.actor.use_dynamic_bsz=True \
    actor_rollout_ref.actor.calculate_entropy=False \
    actor_rollout_ref.actor.ppo_max_token_len_per_gpu=9216 \
    actor_rollout_ref.actor.veomni.param_offload=True \
    actor_rollout_ref.actor.veomni.optimizer_offload=True \
    actor_rollout_ref.actor.veomni.enable_full_shard=True \
    actor_rollout_ref.actor.veomni.ulysses_parallel_size=4 \
    actor_rollout_ref.actor.veomni.expert_parallel_size=1 \
    actor_rollout_ref.actor.veomni.attn_implementation=flash_attention_2 \
    'trainer.logger=["console","wandb"]' \
    trainer.project_name=verl_async_skd_qwen35_webgym \
    trainer.experiment_name=qwen35_9b_to_27b_async_skd_webgym \
    trainer.default_local_dir=/home/sogang_nlpy/verl/checkpoints/verl_async_skd_qwen35_webgym/qwen35_9b_to_27b_async_skd_webgym_counter_tool \
    trainer.rollout_data_dir=/home/sogang_nlpy/verl/logs/rollout_data/webgym_async_skd_${RUN_TS} \
    trainer.n_gpus_per_node=4 \
    trainer.nnodes=1 \
    trainer.val_before_train=False \
    trainer.resume_mode=auto \
    trainer.save_freq=5 \
    trainer.test_freq=5 \
    trainer.total_epochs=100 \
    trainer.total_training_steps=10000 \
    +trainer.use_legacy_worker_impl=disable \
    "$@"
